name: gk_backend
description: A server-side application for AptiGo.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.0.0

dependencies:
  mongo_dart: ^0.10.5
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  mailer: ^6.6.0
  # dotenv is not strictly used in server.dart (manual loading), but good to have if you refactor.
  # flutter_dotenv is NOT compatible with server.

dev_dependencies:
  lints: ^2.0.0
